package cjb.api.asm;

import java.util.Arrays;

import com.google.common.eventbus.EventBus;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

public class CJBASMModContainer extends DummyModContainer {
	
	public CJBASMModContainer() {
        super(new ModMetadata());
        ModMetadata myMeta = super.getMetadata();
        myMeta.autogenerated = true;
        myMeta.authorList = Arrays.asList(new String[] { "CJB" });
        myMeta.modId = "<CJB ASM>";
        myMeta.version = "000";
        myMeta.name = myMeta.description = "<CJB ASM Data Initialization>";
	}
	
	@Override
	public boolean registerBus(EventBus bus, LoadController controller)
    {
		return true;
    }
}
